- name: configure yum erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: configure yum rabbitmq repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start and enable rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

# - name: create rabbitmq user
#   ansible.builtin.command: "rabbitmqctl add_user {{rq_user}} {{rq_password}}"

- name: create rabbitmq user
  ansible.builtin.command: rabbitmqctl add_user {{ rq_user }} {{ rq_password }}
  register: add_user_output
  failed_when: >
    add_user_output.rc != 0 and
    'already exists' not in add_user_output.stderr

- name: set permissions
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"