- name: TAsk level variables
  hosts: localhost
  tasks:
    - name: play level variables display
      vars:
       movie: salaar
       hero: prabhas
      ansible.builtin.debug:
        msg: "I love {{hero}} acted {{movie}} very much"