- name: variables from ptompt
  hosts: localhost
  vars_prompt:
  - name: Movie name
    prompt: please enter movie name
    private: false
  - name: hero name
    prompt: please enter hero name
    private: true
  tasks:
    - name: print and debug values
      ansible.builtin.debug:
        msg: "I love {{hero}} acted {{movie}} very much"